In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("weatherAUS.csv")
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [3]:
x=data.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
print(x)
y=data.iloc[:,-1].values
y=y.reshape(-1,1)
print(y)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]
[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


**Dealing with Illegal Dataset**

In [4]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)

In [5]:
print(x)
print(y)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]
[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


Encoding Dataset


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
le1=LabelEncoder()
x[:,4]=le1.fit_transform(x[:,4])
le2=LabelEncoder()
x[:,6]=le2.fit_transform(x[:,6])
le3=LabelEncoder()
x[:,7]=le3.fit_transform(x[:,7])
le4=LabelEncoder()
x[:,-1]=le4.fit_transform(x[:,-1])
le5=LabelEncoder()
y=le5.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
print(x)
print(y)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]
[0 0 0 ... 0 0 0]


Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.53166617,  0.19132753, -0.04135977, ..., -0.01407077,
         0.02310362, -0.52979545],
       [-1.53166617, -0.75105231,  0.26874452, ...,  0.03244663,
         0.387799  , -0.52979545],
       [-1.53166617,  0.11279588,  0.35331842, ...,  0.62166712,
         0.22733303, -0.52979545],
       ...,
       [ 1.20928479, -1.06517892,  0.52246622, ..., -0.69632607,
         0.65037966, -0.52979545],
       [ 1.20928479, -0.68822699,  0.53656187, ..., -0.29317521,
         0.63579185, -0.52979545],
       [ 1.20928479,  0.42692249, -0.45013361, ..., -0.30868102,
        -0.10818671, -0.52979545]])

Splitting Dataset

In [9]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [10]:
# print(x_train)

Deep Learning Model

In [11]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import RepeatedKFold
from sklearn.metrics import accuracy_score
from numpy import mean
from numpy import std

In [12]:
# x_train.shape
# y_train.shape

In [13]:
def get_model(ip,op):
  model=Sequential()
  model.add(Dense(32,activation='relu',input_dim=ip,kernel_initializer='he_uniform'))
  model.add(Dense(op,activation='sigmoid'))
  model.compile(loss='binary_crossentropy',optimizer='adam')
  return model

In [14]:



print(y.shape)
print(x.shape)

(145460,)
(145460, 19)


In [22]:
from enum import auto
def eval_model(x,y):
  res=list()
  

  cv=RepeatedKFold(n_splits=10,n_repeats=10,random_state=442)
  
  for train,test in cv.split(x):
    x_train,x_test=x[train],x[test]
    y_train,y_test=y[train],y[test]
    
    model=get_model(19,1)
    model.fit(x_train,y_train,verbose=0,epochs=3)
    pred= model.predict(x_test)
    print(y_test)
    print(pred)
    pred=pred.round()
    print(pred)
    acc=accuracy_score(y_test,pred)

    print('>%.3f'%acc)
    res.append(acc)
  return res

res=eval_model(x,y)

print('Accuracy: %.3f (%.3f)' % (mean(res), std(res)))

[0 0 0 ... 0 0 0]
[[0.03042266]
 [0.04184635]
 [0.0543189 ]
 ...
 [0.05371887]
 [0.02421694]
 [0.02617479]]
>0.845
[0 0 0 ... 0 0 0]
[[0.00952974]
 [0.06607278]
 [0.02567066]
 ...
 [0.0584588 ]
 [0.04175726]
 [0.09228723]]
>0.849
[0 0 0 ... 0 0 0]
[[0.0267458 ]
 [0.05361764]
 [0.6070007 ]
 ...
 [0.05354795]
 [0.01142679]
 [0.00722526]]
>0.848
[0 1 1 ... 0 0 0]
[[0.10446363]
 [0.2657142 ]
 [0.04991033]
 ...
 [0.02395663]
 [0.00914656]
 [0.01497247]]
>0.849
[0 0 0 ... 0 0 0]
[[0.03550984]
 [0.05591264]
 [0.01618266]
 ...
 [0.02312055]
 [0.02425275]
 [0.00888837]]
>0.845
[0 0 0 ... 0 0 0]
[[0.01678767]
 [0.06892557]
 [0.02104031]
 ...
 [0.01253964]
 [0.0190494 ]
 [0.0268923 ]]
>0.846
[0 0 0 ... 0 0 0]
[[0.2735954 ]
 [0.20601161]
 [0.09250688]
 ...
 [0.00839407]
 [0.08184492]
 [0.00447656]]
>0.847
[1 1 0 ... 0 0 0]
[[0.36731797]
 [0.6183832 ]
 [0.04120156]
 ...
 [0.00693431]
 [0.01889014]
 [0.00931939]]
>0.846
[0 0 0 ... 0 0 0]
[[0.0692971 ]
 [0.01759505]
 [0.05752705]
 ...
 [0.00844967]
 